"""Generates the agent work package (.ai/BUILD_BRIEF.md).

After the business setup is sufficiently complete, the Factory hands the coding
agent a compact, controlled brief. The agent should be able to start from this
alone — it must never need to interview the employee about software
architecture.

Deliberately EXCLUDED: raw confidential rows. The brief carries structure,
approved meaning and routing, never business data (Constitution Part 30.5).
"""

from __future__ import annotations

import tomllib
from pathlib import Path

from factory import approvals
from factory.questionnaire import HUMAN_OWNED

REPO_ROOT = Path(__file__).resolve().parent.parent
BRIEF_PATH = REPO_ROOT / ".ai" / "BUILD_BRIEF.md"

#: What a new report may change, and what it must not. This table is the
#: difference between a factory and a pile of copy-pasted demos.
VARIATION_POINTS = (
    ("reports/<id>/report.toml", "source roles, sheet/table/range, grain, business "
     "key, history mode, lookback, quality thresholds"),
    ("reports/<id>/mappings.toml", "column aliases, types, merged-cell and duplicate "
     "header handling"),
    ("reports/<id>/metrics.toml", "KPI registry records"),
    ("reports/<id>/sql/clean.sql", "typing and reject rules for your columns"),
    ("reports/<id>/sql/metrics.sql", "the trusted KPI calculations"),
    ("reports/<id>/sql/checks.sql", "report-specific validation"),
    ("reports/<id>/sql/insights.sql", "evidence objects for this report"),
    ("reports/<id>/pipeline.toml", "table names and which SQL file holds what"),
    ("migrations/NNNN_*.sql", "the raw/clean/history table shape for this report"),
)

FACTORY_CORE = (
    ("app/pipeline.py", "the report-agnostic run order"),
    ("app/orchestrator.py", "run lifecycle"),
    ("app/state_machine.py", "legal run states"),
    ("app/data/history.py", "the four load modes and the merge"),
    ("app/data/database.py", "connection and transaction policy"),
    ("app/quality/engine.py", "the check framework"),
    ("app/quality/reconciliation.py", "control totals and the population equation"),
    ("app/local_transport.py", "loopback security"),
    ("tools/", "map, gates, verifiers"),
    ("contracts/", "run states, error codes, schemas"),
    ("acceptance/gates.yaml", "the gate ledger"),
)


def generate(report_id: str, *, root: Path | None = None) -> str:
    """Build the brief for one report and write it to `.ai/BUILD_BRIEF.md`."""
    reports_root = (root or REPO_ROOT) / "reports"
    directory = reports_root / report_id
    config_path = directory / "report.toml"
    if not config_path.exists():
        raise FileNotFoundError(f"no report contract at {config_path}")

    config = tomllib.loads(config_path.read_text("utf-8"))
    decisions = _decisions_from(config)
    statuses = approvals.status_for(
        report_id, decisions, mode=config.get("mode", "prototype"))

    confirmed = [s for s in statuses if s.state == "CONFIRMED"]
    pending = [s for s in statuses if s.state != "CONFIRMED"]

    lines = [
        f"# BUILD BRIEF — {report_id}",
        "",
        "_Generated by `PROJECT_TOOL factory brief`. Regenerate after any approval._",
        "",
        "You are a **factory worker, not an architect**. A proven pipeline already",
        "exists and is tested end to end. Your job is to adapt its controlled",
        "variation points to this report — not to design a pipeline again.",
        "",
        "## Business objective",
        "",
        f"- **Report:** {report_id}",
        f"- **Audience:** {config.get('output', {}).get('audience', 'PENDING_APPROVAL')}",
        f"- **Load mode:** {config.get('load_mode', 'PENDING_APPROVAL')}",
        f"- **Mode:** {config.get('mode', 'prototype')}",
        "",
        "## Approved decisions",
        "",
    ]
    if confirmed:
        lines += ["| Decision | Value | Approved by |", "|---|---|---|"]
        lines += [f"| {s.decision_id} | `{decisions[s.decision_id]}` | {s.approved_by} |"
                  for s in confirmed]
    else:
        lines.append("_None yet. Production work is blocked until a human approves._")

    lines += ["", "## Pending decisions — BLOCKING", ""]
    if pending:
        lines += ["| Decision | State | What is needed |", "|---|---|---|"]
        lines += [f"| {s.decision_id} | **{s.state}** | {s.detail} |" for s in pending]
        lines += ["", "> You may PROPOSE values for these and label them",
                  "> `SUGGESTED — HUMAN APPROVAL REQUIRED`. You may never approve them."]
    else:
        lines.append("_None. Every human-owned decision has a binding approval._")

    lines += [
        "",
        "## Start from the Golden Reference",
        "",
        "`reports/_REFERENCE/` is a complete, working, tested report. It processes",
        "three periods, handles a correction, a duplicate, a rejected row, a warning",
        "and a blocking failure, and its numbers are verified against hand-derived",
        "expectations in `tests/expected/reference/expected.json`.",
        "",
        "**Copy its pattern, configure it, extend it. Do not redesign it.**",
        "",
        "### Variation points — these are yours to change",
        "",
        "| File | What varies |",
        "|---|---|",
    ]
    lines += [f"| `{path}` | {what} |" for path, what in VARIATION_POINTS]

    lines += [
        "",
        "### Factory Core — do NOT modify for an ordinary report",
        "",
        "| File | Why it is shared |",
        "|---|---|",
    ]
    lines += [f"| `{path}` | {why} |" for path, why in FACTORY_CORE]
    lines += [
        "",
        "If you believe a report genuinely needs a Factory Core change, that is a",
        "contract change with a version bump — not a copy-paste. Say so explicitly.",
        "",
        "## Tests you must run",
        "",
        "```text",
        "python3 -m unittest discover -s tests -t .",
        "PROJECT_TOOL doctor",
        f"PROJECT_TOOL report validate --id {report_id} --mode production",
        "PROJECT_TOOL factory validate",
        "```",
        "",
        "## Acceptance gates this work must advance",
        "",
        "```text",
        "GATE_BUSINESS_DEFINITION_APPROVED   every human-owned decision approved",
        "GATE_CONTROL_TOTAL                  difference exactly zero",
        "GATE_HISTORY_IDEMPOTENT             identical rerun changes nothing",
        "GATE_POPULATION_EQUATION            source = accepted + rejected + filtered",
        "GATE_GOLDEN_METRICS                 known answers still known",
        "```",
        "",
        "## Contracts at risk",
        "",
        "- `contracts/report_config.schema.json` — if you add a configuration field",
        "- `contracts/dashboard.schema.json` — if the dashboard shape changes",
        "- `migrations/` — a new report adds a migration; it never edits an applied one",
        "",
        "## What this brief deliberately does not contain",
        "",
        "Raw business rows. The brief carries structure, approved meaning and",
        "routing only (Part 30.5). If you need to see data, use the synthetic",
        "fixtures under `tests/fixtures/`.",
        "",
    ]

    text = "\n".join(lines)
    target = (root or REPO_ROOT) / ".ai" / "BUILD_BRIEF.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return text


def _decisions_from(config: dict) -> dict:
    """Pull the human-owned values out of a report contract."""
    history = config.get("history", {})
    quality = config.get("quality", {})
    output = config.get("output", {})
    found = {
        "business_key": history.get("business_key"),
        "load_mode": config.get("load_mode"),
        "lookback_days": history.get("lookback_days"),
        "deletion_rule": history.get("deletion_rule"),
        "control_total_column": quality.get("control_total_column"),
        "storage_allowed": output.get("storage_allowed"),
    }
    return {key: value for key, value in found.items()
            if key in HUMAN_OWNED or key in (
                "business_key", "load_mode", "lookback_days", "deletion_rule",
                "control_total_column", "storage_allowed")}
