"""Generates a report's technical contract from the business interview.

The employee never learns that `report.toml`, `mappings.toml`, `quality.toml`
or `metrics.toml` exist. They answer questions; this module writes the files.

Every value it cannot derive from an answer is written as `PENDING_APPROVAL`.
The generator translates — it never invents (Constitution Part 41.3).
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from factory.questionnaire import Interview

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS_ROOT = REPO_ROOT / "reports"
REFERENCE_DIR = REPORTS_ROOT / "_REFERENCE"
TEMPLATE_DIR = REPORTS_ROOT / "_TEMPLATE"

SENTINEL = "PENDING_APPROVAL"


class GeneratorError(RuntimeError):
    """The contract cannot be generated safely."""


@dataclass
class GeneratedProject:
    report_id: str
    directory: Path
    files_written: list[str]
    pending_decisions: list[str]

    @property
    def ready_for_production(self) -> bool:
        return not self.pending_decisions


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(f'"{str(item)}"' for item in value) + "]"
    return f'"{value}"'


def generate(
    interview: Interview,
    *,
    title: str,
    reports_root: Path | None = None,
    seed_from_reference: bool = True,
) -> GeneratedProject:
    """Create `reports/<id>/` from the interview answers.

    Seeded from the Golden Reference so the new report starts from a KNOWN-GOOD
    shape. That is the whole teaching mechanism: copy the proven pattern, then
    configure it — do not design the pipeline again.
    """
    root = reports_root or REPORTS_ROOT
    destination = root / interview.report_id
    if destination.exists():
        raise GeneratorError(f"reports/{interview.report_id}/ already exists")

    source = REFERENCE_DIR if seed_from_reference else TEMPLATE_DIR
    if not source.exists():
        raise GeneratorError(f"missing seed project: {source}")

    shutil.copytree(source, destination)
    contract = interview.technical_contract()
    written: list[str] = []

    report_toml = _render_report_toml(interview, contract, title)
    (destination / "report.toml").write_text(report_toml, encoding="utf-8")
    written.append("report.toml")

    definition = _render_definition(interview, contract, title)
    (destination / "report_definition.md").write_text(definition, encoding="utf-8")
    written.append("report_definition.md")

    pending = sorted(
        key for key, value in contract.items()
        if value == SENTINEL or (isinstance(value, str) and value == SENTINEL))
    return GeneratedProject(interview.report_id, destination, written, pending)


def _render_report_toml(interview: Interview, contract: dict, title: str) -> str:
    reference = (REFERENCE_DIR / "report.toml").read_text("utf-8")
    lines = [
        f"# {title}",
        "#",
        "# Generated by the Factory from a business interview. The employee",
        "# answered plain questions; this file is the technical translation.",
        "#",
        "# Values shown as PENDING_APPROVAL still need a named human. An agent",
        "# may propose them but may never resolve them (Part 41.3).",
        "",
        f'report_id      = "{interview.report_id}"',
        "report_version = 1",
        'mode           = "prototype"',
        f"load_mode      = {_toml_value(contract['load_mode'])}",
        'timezone       = "PENDING_APPROVAL"',
        'currency       = "PENDING_APPROVAL"',
        "",
    ]
    # Reuse the reference's proven [excel] / [extraction] defaults verbatim.
    inside = False
    for line in reference.splitlines():
        if line.startswith("[excel]"):
            inside = True
        elif line.startswith("[history]"):
            inside = False
        if inside:
            lines.append(
                line.replace('adapter            = "fixture"',
                             'adapter            = "com"'))
    lines += [
        "",
        "[history]",
        f"business_key   = {_toml_value(contract['business_key'])}",
        'event_date     = "PENDING_APPROVAL"',
        f"lookback_days  = {_toml_value(contract['lookback_days'])}",
        f"deletion_rule  = {_toml_value(contract['deletion_rule'])}",
        "",
        "[quality]",
        "required_columns_block   = true",
        "max_duplicate_key_rate   = 0.0",
        "max_required_null_rate   = 0.0",
        'max_row_count_change_pct = "PENDING_APPROVAL"',
        f"control_total_column     = {_toml_value(contract['control_total_column'])}",
        "approved_categories      = []",
        "",
        "[output]",
        f"audience             = {_toml_value(contract.get('purpose', SENTINEL))}",
        f"storage_allowed      = {_toml_value(contract['storage_allowed'])}",
        'retention_days       = "PENDING_APPROVAL"',
        "ai_narrative_allowed = false",
        "",
        "# Approvals are recorded in factory/approvals/<report_id>.approvals.jsonl",
        "# with a hash of the exact approved value. Changing a value above voids",
        "# its approval automatically.",
        "[approvals]",
    ]
    for key in ("business_key", "load_mode", "deletion_rule",
                "control_total_column", "storage_allowed"):
        lines.append(f'{key} = {{ approved_by = "", approved_at = "", evidence = "" }}')
    return "\n".join(lines) + "\n"


def _render_definition(interview: Interview, contract: dict, title: str) -> str:
    rows = "\n".join(
        f"| {item['item']} | {item['understanding']} | {item['explanation']} |"
        for item in interview.understanding_review())
    return f"""# Report definition — {title}

> Generated by the Factory from the business interview. **The employee approves
> the meaning below, not the implementation.** Anything reading
> `PENDING_APPROVAL` still needs a named human (Constitution Part 41).

## What the system understood

| Item | Understanding | What this means |
|---|---|---|
{rows}

## Purpose

{contract.get('purpose', SENTINEL)}

## The decision this dashboard supports

{contract.get('dashboard_decision', SENTINEL)}

## Approval record

Approvals live in `factory/approvals/{interview.report_id}.approvals.jsonl`,
each bound to a hash of the exact approved value. If a value changes after
approval, the approval stops counting and the item returns to
`NEEDS YOUR APPROVAL`.

Run `PROJECT_TOOL factory status --id {interview.report_id}` to see the current
state of every decision.
"""
