"""FACTORY CORE — the report-agnostic pipeline (Constitution Parts 6, 12.1).

This module is the answer to "do not make every future agent reinvent the
pipeline". It executes the full run order for **any** report whose contract
follows `reports/<id>/report.toml` + `pipeline.toml`.

    extract -> stage -> quality -> clean -> history -> archive
            -> metrics -> insights -> dashboard JSON -> HTML -> verify

**Do not edit this file to add a report.** Everything a report needs to vary is
configuration or its own `sql/*.sql`. If you find yourself editing here for one
report, that is the signal you have found a genuinely missing Factory Core
capability — and that is a contract change, not a copy-paste.

The run advances through `app/state_machine.py`, so an illegal ordering raises
instead of silently producing a half-built result.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any

from app.analytics.runner import SqlRunner, as_decimal, weighted_rate_ppm
from app.data.archive import archive_history
from app.data.database import Database
from app.data.history import HistoryEngine, HistoryResult
from app.data.migrations import migrate
from app.data.staging import LINEAGE_COLUMNS, StagingWriter
from app.errors import AppError
from app.quality.engine import FAIL, QualityEngine, QualityReport
from app.quality.quarantine import (
    EXACT_DUPLICATE, NEGATIVE_MEASURE, QuarantinedRow, quarantine_rows,
    summary_by_reason,
)
from app.quality.reconciliation import (
    ControlTotal, Population, check_control_total, check_population,
)
from app.state_machine import RunStateMachine


class ReportContract:
    """One report's approved configuration, loaded once."""

    def __init__(self, directory: Path) -> None:
        self.directory = Path(directory)
        self.report = tomllib.loads((self.directory / "report.toml").read_text("utf-8"))
        self.pipeline = tomllib.loads((self.directory / "pipeline.toml").read_text("utf-8"))

    @property
    def report_id(self) -> str:
        return self.report["report_id"]

    @property
    def sql_directory(self) -> Path:
        return self.directory / "sql"

    @property
    def uses_fixture_adapter(self) -> bool:
        return self.report.get("excel", {}).get("adapter") == "fixture"

    @property
    def business_columns(self) -> list[str]:
        return list(self.pipeline["columns"]["business"])

    @property
    def key_columns(self) -> list[str]:
        return list(self.report["history"]["business_key"])

    def table(self, name: str) -> str:
        return self.pipeline["tables"][name]

    def sql_file(self, name: str) -> str:
        return self.pipeline["sql"][name]


@dataclass
class RunOutcome:
    run_id: str
    status: str
    quality_status: str
    history: HistoryResult = field(default_factory=HistoryResult)
    rows_extracted: int = 0
    rows_rejected: int = 0
    rows_filtered: int = 0
    control_totals: list[ControlTotal] = field(default_factory=list)
    quality_report: QualityReport | None = None
    dashboard: dict[str, Any] | None = None
    error_code: str | None = None
    error_message: str | None = None
    demo_data: bool = False
    quarantine: dict[str, int] = field(default_factory=dict)

    @property
    def succeeded(self) -> bool:
        return self.status == "COMPLETE"


class Pipeline:
    """Executes one run of one report."""

    def __init__(
        self,
        database: Database,
        contract: ReportContract,
        *,
        application_version: str = "0.0.0",
    ) -> None:
        self.database = database
        self.contract = contract
        self.application_version = application_version
        self.sql = SqlRunner(database, contract.sql_directory)

    # -- setup -------------------------------------------------------------

    def prepare(self) -> None:
        migrate(self.database, application_version=self.application_version)

    # -- the run -----------------------------------------------------------

    def run(self, run_id: str, port: Any, *, requested_period: str | None = None) -> RunOutcome:
        machine = RunStateMachine()
        outcome = RunOutcome(run_id=run_id, status="RUNNING", quality_status="",
                             demo_data=self.contract.uses_fixture_adapter)
        started = datetime.now(timezone.utc)

        try:
            machine.to("CHECKING_SOURCE")
            machine.to("OPENING_EXCEL")
            machine.to("EXTRACTING")

            outcome.rows_extracted = self._stage(run_id, port)

            machine.to("STAGING")
            machine.to("VALIDATING")

            quality, population, controls = self._validate(run_id, outcome)
            outcome.quality_report = quality
            outcome.quality_status = quality.status
            outcome.control_totals = controls
            quality.persist(self.database)

            if quality.status == FAIL:
                # Trusted history is NOT touched, and the last approved
                # dashboard stays exactly where it is (Part 12.6).
                machine.to("FAILED")
                first = quality.blocking_failures()[0]
                outcome.status = "FAILED"
                outcome.error_code = self._error_code_for(first.check_id)
                outcome.error_message = first.message
                self._record_run(outcome, started)
                return outcome

            machine.to("CLEANING")
            machine.to("UPDATING_HISTORY")
            outcome.history = self._update_history(run_id, requested_period)

            machine.to("ARCHIVING")
            self._archive()

            machine.to("CALCULATING")
            metrics = self._metrics()

            machine.to("BUILDING_INSIGHTS")
            insights = self._insights(metrics)

            machine.to("BUILDING_JSON")
            outcome.dashboard = self._dashboard(metrics, insights, outcome)

            machine.to("BUILDING_DASHBOARD")
            machine.to("VERIFYING")
            machine.to("COMPLETE")
            outcome.status = "COMPLETE"

        except AppError as error:
            outcome.status = "FAILED"
            outcome.error_code = error.code
            outcome.error_message = str(error)
            raise
        finally:
            if outcome.status in ("COMPLETE", "FAILED"):
                self._record_run(outcome, started)

        return outcome

    # -- stages ------------------------------------------------------------

    def _stage(self, run_id: str, port: Any) -> int:
        writer = StagingWriter(
            self.database, self.contract.table("raw"), self.contract.business_columns)
        lineage = port.lineage()
        result = writer.stage(port, lineage)
        return result.rows_staged

    def _validate(
        self, run_id: str, outcome: RunOutcome
    ) -> tuple[QualityReport, Population, list[ControlTotal]]:
        quality = QualityReport(run_id=run_id)
        engine = QualityEngine(self.database, self.contract.report)
        raw_table = self.contract.table("raw")
        checks = self.contract.sql_file("checks")
        clean_sql = self.contract.sql_file("clean")

        present = [
            column for column in self.database.columns_of(raw_table)
            if column not in LINEAGE_COLUMNS
        ]
        staged_non_null = [
            column for column in present
            if (self.database.scalar(
                f"SELECT count(*) FROM {raw_table} WHERE _run_id = ? "
                f"AND {column} IS NOT NULL", [run_id]) or 0) > 0
        ]
        engine.check_required_columns(
            quality, staged_non_null, self.contract.key_columns
            + [self.contract.report["quality"]["control_total_column"]])

        if quality.status == FAIL:
            # A missing required column makes every later check meaningless.
            source_rows = int(self.sql.scalar(checks, "source_row_count", [run_id]) or 0)
            return quality, Population(source_rows, 0, 0, 0), []

        engine.check_no_blank_business_key(
            quality, raw_table, run_id, self.contract.key_columns)

        rejected = self._quarantine_rejects(run_id, clean_sql)
        filtered = self._quarantine_duplicates(run_id, clean_sql)
        outcome.rows_rejected = rejected
        outcome.rows_filtered = filtered

        self.sql.run_script(clean_sql, "build_clean", [run_id])

        engine.check_duplicate_business_keys(
            quality, self.contract.table("clean"), run_id, self.contract.key_columns)
        engine.check_non_negative(
            quality, raw_table, run_id, self.contract.pipeline["columns"]["measures"])
        engine.check_category_allowed(
            quality, self.contract.table("clean"), run_id,
            self.contract.pipeline["columns"]["category"],
            self.contract.report["quality"].get("approved_categories", []))

        source_rows = int(self.sql.scalar(checks, "source_row_count", [run_id]) or 0)
        accepted_rows = int(self.sql.scalar(clean_sql, "clean_row_count", [run_id]) or 0)
        population = Population(
            source_rows=source_rows,
            accepted_rows=accepted_rows,
            rejected_rows=rejected,
            intentionally_filtered_rows=filtered,
            filter_reasons=(("exact_duplicate", filtered),),
        )
        check_population(quality, population)

        control_column = self.contract.report["quality"]["control_total_column"]
        source_value = as_decimal(self.sql.scalar(checks, "source_control_total", [run_id]))
        accepted_value = as_decimal(self.sql.scalar(checks, "accepted_control_total", [run_id]))
        rejected_value = as_decimal(self.sql.scalar(checks, "rejected_control_total", [run_id]))
        filtered_value = as_decimal(self.sql.scalar(checks, "filtered_control_total", [run_id]))

        # The control total must account for EVERY source row, including the
        # ones we deliberately excluded. Comparing only accepted rows would let
        # a silent drop pass unnoticed — which is the whole failure this check
        # exists to prevent (Part 9.4).
        control = ControlTotal(
            name=control_column,
            source_value=source_value,
            database_value=accepted_value + rejected_value + filtered_value,
        )
        check_control_total(quality, control)

        outcome.quarantine = summary_by_reason(self.database, run_id)
        return quality, population, [control]

    def _quarantine_rejects(self, run_id: str, clean_sql: str) -> int:
        rows = self.sql.run_named(clean_sql, "negative_measure_rows", [run_id])
        payload = [
            QuarantinedRow(
                source_row=row[0], reason_code=NEGATIVE_MEASURE,
                raw_values=dict(zip(self.contract.business_columns, row[1:])))
            for row in rows
        ]
        return quarantine_rows(self.database, run_id, self.contract.report_id, payload)

    def _quarantine_duplicates(self, run_id: str, clean_sql: str) -> int:
        rows = self.sql.run_named(clean_sql, "exact_duplicate_rows", [run_id])
        payload = [
            QuarantinedRow(
                source_row=row[0], reason_code=EXACT_DUPLICATE,
                raw_values=dict(zip(self.contract.business_columns, row[1:])))
            for row in rows
        ]
        return quarantine_rows(self.database, run_id, self.contract.report_id, payload)

    def _update_history(self, run_id: str, requested_period: str | None) -> HistoryResult:
        history_config = self.contract.report["history"]
        engine = HistoryEngine(
            self.database,
            history_table=self.contract.table("history"),
            clean_table=self.contract.table("clean"),
            business_columns=self.contract.business_columns,
            key_columns=self.contract.key_columns,
            event_date_column=history_config["event_date"],
        )
        return engine.apply(
            run_id,
            load_mode=self.contract.report["load_mode"],
            lookback_days=int(history_config.get("lookback_days") or 0),
            deletion_rule=history_config.get("deletion_rule", "ignore"),
            requested_period=requested_period,
        )

    def _archive(self) -> None:
        archive_root = Path("workspace") / "archive" / self.contract.report_id
        archive_history(
            self.database,
            history_table=self.contract.table("history"),
            report_id=self.contract.report_id,
            archive_root=archive_root,
            event_date_column=self.contract.report["history"]["event_date"],
        )

    def _metrics(self) -> dict[str, Any]:
        metrics_file = self.contract.sql_file("metrics")
        produced = as_decimal(self.sql.scalar(metrics_file, "produced_total"))
        defects = as_decimal(self.sql.scalar(metrics_file, "defect_total"))
        top = self.sql.run_named(metrics_file, "top_contributor")
        return {
            "produced_total": produced,
            "defect_total": defects,
            "active_rows": int(self.sql.scalar(metrics_file, "active_row_count") or 0),
            "defect_rate_ppm": weighted_rate_ppm(defects, produced),
            "trend": self.sql.run_named(metrics_file, "trend_by_date"),
            "pareto": self.sql.run_named(metrics_file, "pareto_by_model"),
            "top_contributor": top[0] if top else None,
        }

    def _insights(self, metrics: dict[str, Any]) -> list[dict[str, Any]]:
        """Evidence objects first, sentences second (Part 26.6)."""
        insights_file = self.contract.sql_file("insights")
        evidence = self.sql.run_named(insights_file, "period_change_evidence")
        results: list[dict[str, Any]] = []

        if evidence and evidence[0][3] is not None:
            (current_period, current_produced, current_defects,
             comparison_period, comparison_produced, comparison_defects) = evidence[0]
            current_rate = weighted_rate_ppm(current_defects, current_produced)
            comparison_rate = weighted_rate_ppm(comparison_defects, comparison_produced)
            if current_rate is not None and comparison_rate is not None:
                change = current_rate - comparison_rate
                percent = (change / comparison_rate * 100) if comparison_rate else None
                results.append({
                    "id": "period_change",
                    "type": "period_change",
                    "metric_id": "defect_rate_ppm",
                    "current_period": str(current_period),
                    "current": float(current_rate),
                    "comparison_period": str(comparison_period),
                    "comparison": float(comparison_rate),
                    "change_absolute": float(change),
                    "change_percent": float(percent) if percent is not None else None,
                    "confidence": "verified",
                    "evidence_refs": ["metric:defect_rate_ppm", "sql:period_change_evidence"],
                    "text": (
                        f"Defect rate moved from {comparison_rate:.0f} to "
                        f"{current_rate:.0f} PPM between {comparison_period} and "
                        f"{current_period}."),
                })

        contributors = self.sql.run_named(insights_file, "top_contributor_evidence")
        if contributors:
            model, defect_qty, share = contributors[0]
            results.append({
                "id": "top_contributor",
                "type": "contributor",
                "metric_id": "defect_qty",
                "current": float(as_decimal(defect_qty)),
                "confidence": "verified",
                "evidence_refs": ["metric:defect_qty", "sql:top_contributor_evidence"],
                # "contributor", never "root cause" (Part 26.12).
                "text": (f"{model} is the largest contributor with "
                         f"{as_decimal(defect_qty)} defects "
                         f"({as_decimal(share):.1f}% of the total). "
                         f"Treat it as an investigation priority, not a confirmed cause."),
            })
        return results[:5]

    def _dashboard(
        self, metrics: dict[str, Any], insights: list[dict[str, Any]], outcome: RunOutcome
    ) -> dict[str, Any]:
        rate = metrics["defect_rate_ppm"]
        quality = outcome.quality_report
        trend = metrics["trend"]

        return {
            "schema_version": "1.0",
            "demo_data": outcome.demo_data,
            "unapproved_definitions": self._has_unapproved_definitions(),
            "report": {
                "id": self.contract.report_id,
                "title": self.contract.pipeline["dashboard"]["title"],
                "period": str(trend[-1][0]) if trend else "",
                "version": self.contract.report["report_version"],
            },
            "freshness": {
                "data_date": str(trend[-1][0]) if trend else "",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "run_id": outcome.run_id,
                "is_partial": False,
            },
            "quality": {
                "status": outcome.quality_status,
                "passed": quality.passed if quality else 0,
                "warnings": quality.warnings if quality else 0,
                "failed": quality.failed if quality else 0,
                "control_totals": [
                    {"name": control.name,
                     "source_value": float(control.source_value),
                     "database_value": float(control.database_value),
                     "difference": float(control.difference)}
                    for control in outcome.control_totals
                ],
            },
            "filters": {
                "definitions": [
                    {"id": "model_code", "label": "Model", "type": "multi"},
                    {"id": "line", "label": "Line", "type": "multi"},
                ],
                "active": {},
            },
            "kpis": [
                self._kpi("produced_total", "Produced", metrics["produced_total"],
                          "units", "up_good"),
                self._kpi("defect_total", "Defects", metrics["defect_total"],
                          "units", "down_good"),
                self._kpi("defect_rate_ppm", "Defect rate", rate, "PPM", "down_good"),
            ],
            "charts": [
                {
                    "id": "trend",
                    "title": "Is quality improving over time?",
                    "type": "line",
                    "dimensions": ["production_date"],
                    "series": [{
                        "name": "Defect rate (PPM)",
                        "points": [
                            {"x": str(row[0]),
                             "y": float(as_decimal(row[3])) if row[3] is not None else None}
                            for row in trend
                        ],
                    }],
                    "unit": "PPM",
                    "accessible_summary": self._trend_summary(trend),
                    "evidence_ref": "sql:trend_by_date",
                },
                {
                    "id": "pareto",
                    "title": "Which models explain most of the defects?",
                    "type": "pareto",
                    "dimensions": ["model_code"],
                    "series": [{
                        "name": "Defects",
                        "points": [
                            {"x": row[0], "y": float(as_decimal(row[1])),
                             "cumulative_pct": float(as_decimal(row[2]))}
                            for row in metrics["pareto"]
                        ],
                    }],
                    "unit": "units",
                    "accessible_summary": self._pareto_summary(metrics["pareto"]),
                    "evidence_ref": "sql:pareto_by_model",
                },
            ],
            "tables": [],
            "insights": insights,
            "actions": [],
            "lineage": {
                "sources": [{"rows": outcome.rows_extracted}],
                "rows": metrics["active_rows"],
                "mapping_version": "1",
                "metric_version": "1",
            },
            "downloads": [],
        }

    def _kpi(self, kpi_id: str, label: str, value: Any, unit: str, direction: str) -> dict:
        numeric = None if value is None else float(as_decimal(value))
        return {
            "id": kpi_id,
            "label": label,
            "value": numeric,
            # A null value shows as an em dash, never a false zero (Part 26.5).
            "display": "—" if numeric is None else f"{numeric:,.0f}",
            "unit": unit,
            "period": "",
            "comparison": None,
            "direction": direction,
            "status": "neutral",
            "evidence_ref": f"metric:{kpi_id}",
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }

    def _trend_summary(self, trend: list[tuple]) -> str:
        if not trend:
            return "No trend data available."
        return "; ".join(
            f"{row[0]}: {as_decimal(row[3]):.0f} PPM" if row[3] is not None
            else f"{row[0]}: no rate" for row in trend)

    def _pareto_summary(self, pareto: list[tuple]) -> str:
        if not pareto:
            return "No contributor data available."
        return "; ".join(
            f"{row[0]}: {as_decimal(row[1]):.0f} defects "
            f"({as_decimal(row[2]):.1f}% cumulative)" for row in pareto)

    def _has_unapproved_definitions(self) -> bool:
        return "PENDING_APPROVAL" in (self.contract.directory / "report.toml").read_text("utf-8")

    def _error_code_for(self, check_id: str) -> str:
        if check_id.startswith("structural.required_columns"):
            return "SCHEMA_REQUIRED_COLUMN_MISSING"
        if check_id.startswith("control_total"):
            return "DQ_CONTROL_TOTAL_MISMATCH"
        if check_id.startswith("dataset.duplicate"):
            return "DATA_DUPLICATE_BUSINESS_KEY"
        return "ANALYTICS_TEST_FAILED"

    def _record_run(self, outcome: RunOutcome, started: datetime) -> None:
        self.database.execute(
            "INSERT OR REPLACE INTO sys.run (run_id, report_id, report_version, "
            "application_version, status, stage, started_at, finished_at, "
            "rows_extracted, rows_rejected, rows_inserted, rows_updated, "
            "rows_unchanged, rows_filtered, quality_status, demo_data, "
            "error_code, error_message) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            [outcome.run_id, self.contract.report_id,
             self.contract.report["report_version"], self.application_version,
             outcome.status, outcome.status, started, datetime.now(timezone.utc),
             outcome.rows_extracted, outcome.rows_rejected, outcome.history.inserted,
             outcome.history.updated, outcome.history.unchanged, outcome.rows_filtered,
             outcome.quality_status, outcome.demo_data,
             outcome.error_code, outcome.error_message],
        )


def decimal_or_none(value: Any) -> Decimal | None:
    return None if value is None else as_decimal(value)
