-- name: build_clean
INSERT INTO clean.downtime (event_date,line,event_id,machine,reason,downtime_minutes,planned_flag,business_key_hash,row_content_hash,_run_id,_source_id,_source_file,_source_row_number)
SELECT CAST(r.event_date AS DATE),trim(r.line),trim(r.event_id),trim(r.machine),trim(r.reason),CAST(r.downtime_minutes AS DECIMAL(18,4)),lower(trim(r.planned_flag)) IN ('true','1','yes','y'),md5(concat_ws(chr(31),trim(r.event_date),trim(r.line),trim(r.event_id))),md5(concat_ws(chr(31),trim(r.machine),trim(r.reason),CAST(CAST(r.downtime_minutes AS DECIMAL(18,4)) AS VARCHAR),lower(trim(r.planned_flag)))),r._run_id,r._source_id,r._source_file,r._source_row_number
FROM raw.downtime r WHERE r._run_id=? AND TRY_CAST(r.downtime_minutes AS DECIMAL(18,4))>=0 AND r.event_date IS NOT NULL AND trim(r.event_date)<>'' AND r.line IS NOT NULL AND trim(r.line)<>'' AND r.event_id IS NOT NULL AND trim(r.event_id)<>'' AND r._source_row_number=(SELECT min(r2._source_row_number) FROM raw.downtime r2 WHERE r2._run_id=r._run_id AND r2.event_date=r.event_date AND r2.line=r.line AND r2.event_id=r.event_id AND r2.machine=r.machine AND r2.reason=r.reason AND r2.downtime_minutes=r.downtime_minutes AND r2.planned_flag=r.planned_flag);
-- name: negative_measure_rows
SELECT _source_row_number,event_date,line,event_id,machine,reason,downtime_minutes,planned_flag FROM raw.downtime WHERE _run_id=? AND TRY_CAST(downtime_minutes AS DECIMAL(18,4))<0;
-- name: exact_duplicate_rows
SELECT r._source_row_number,r.event_date,r.line,r.event_id,r.machine,r.reason,r.downtime_minutes,r.planned_flag FROM raw.downtime r WHERE r._run_id=? AND r._source_row_number>(SELECT min(r2._source_row_number) FROM raw.downtime r2 WHERE r2._run_id=r._run_id AND r2.event_date=r.event_date AND r2.line=r.line AND r2.event_id=r.event_id AND r2.machine=r.machine AND r2.reason=r.reason AND r2.downtime_minutes=r.downtime_minutes AND r2.planned_flag=r.planned_flag);
-- name: clean_row_count
SELECT count(*) FROM clean.downtime WHERE _run_id=?;
